### ISSUE TITLE
Route pattern

### ISSUE THREAD

**Issue by newtack** [fastrodev/fastro#10]
I did not see any route patterns. How do I implement

get("/*") pattern for example.

I am trying to do a dev server similar to https://github.com/zhmushan/dev_server/blob/master/mod.ts, which uses ABC, but there doesn't seem to be support for route patterns. What's the equivalent or how do I accomplish this task in fastro?

**Comment by ynwd** [comment]
what do you mean and want to achieve with `/ *` ?

You can get examples of how to use (including routing), here:
https://fastro.dev/examples.html

**Comment by ynwd** [comment]
This issue is closed because it is not active
