### ISSUE TITLE
Question: why req.send?

### ISSUE THREAD

**Issue by huydhoang** [fastrodev/fastro#11]
Hi, I'm trying out Fastro and the development experience seems great.
However, I'm wondering why it is req.send?
Taken from the Fastify docs:

> As the name suggests, .send() is the function that sends the payload to the end user.

Assuming it does the same functionality as reply.send, wouldn't it make more sense to use return, reply.send or response.send?

**Comment by ynwd** [comment]
Fastro `Request` class is extended from [`ServerRequest` ](https://deno.land/std/http/server.ts)
