### ISSUE TITLE
Getting path parameters

### ISSUE THREAD

**Issue by huydhoang** [fastrodev/fastro#12]
I'm trying to get path parameters in a path like this: "/users/:id".
I've been looking around the docs and examples but couldn't find one that has this pattern.
How is it done in Fastro to console.log that id?

**Comment by ynwd** [comment]
> I'm trying to get path parameters in a path like this: "/users/:id".

that feature was removed.

> I've been looking around the docs and examples but couldn't find one that has this pattern.
> How is it done in Fastro to console.log that id?

if you want to get path parameters, you can dynamic parameter
check this: https://fastro.dev/2020/07/02/basic.html
