### ISSUE TITLE
How to modify context in middleware?

### ISSUE THREAD

**Issue by Juribiyan** [fastrodev/fastro#273]
I have created a middleware with intention to be reused in several routes in my fastro project. Its purpose is to read the user's IP and produce a hash identifier for the user then store it in the cookies - or read it from the cookies if it was already stored. I tried to store the hash string `userHash` in the context but in the next handler it is unavailable, i.e. `undefined`. Here's the code:
```typescript
const userHashHandler = async (req: HttpRequest, ctx: Context, next: Next) => {
  const cookies = getCookies(req.headers);
  const userHash = cookies?.hash
  if (!userHash || userHash.length != 44) { // validate the hash (it's sha-256)
    const addr = ctx.info.remoteAddr as Deno.NetAddr
    const ip = addr.hostname
    ctx.userHash = await hash(ip) // newly created hash
  }
  else {
    ctx.userHash = userHash // hash read from cookie
  }
  return next()
}

f.get("/", 
  userHashHandler,
  (_req: HttpRequest, ctx: Context) => {
    // Here I am trying to read userHash from context:
    return new Response(`Your User Hash is <b>${ctx.userHash}</b><br>`, 
    { headers: { "content-type": "text/html" } }  
    )
  }
)
```
Unfortunately this code returns "Your User Hash is **undefined**". What am I doing wrong?

By the way is it possible to also store a cookie in the middleware?

**Comment by ynwd** [comment]
This is the docs for context, btw
https://deno.land/x/fastro@v0.81.5/mod.ts?s=Context

If you want to add new field on the middleware, you can use `HttpRequest`
https://deno.land/x/fastro@v0.81.5/mod.ts?s=HttpRequest
