### ISSUE TITLE
Match trailing slashes

### ISSUE THREAD

**Issue by ghost** [fastrodev/fastro#33]
```typescript
import application, {
  response,
} from "https://deno.land/x/fastro@v0.52.0/server/mod.ts";

const app = application();

app.get("/hello", () => {
  const res = response();
  return res.json({ text: "Hello world" });
});

console.log("Listening on: http://localhost:8000");

await app.serve();
```

This example should match `/hello` and `/hello/`. If this is an intended behaviour there should be at least an option to match trailing slashes as it's a fairly typical situation.

**Comment by ynwd** [comment]
@danteissaias not sure how to implement that request. PR is welcome.

**Comment by danteissaias** [comment]
Have you though about using the URLPattern interface internally instead of regex to match the pathname?
