### ISSUE TITLE
Benchmarks are incorrect

### ISSUE THREAD

**Issue by trivikr** [fastrodev/fastro#8]
**Describe the bug**
The benchmarks shared in https://github.com/fastrodev/fastro#benchmarks are incorrect.
Deno http server serves around 25-40% less req/sec than that of Node.js https://github.com/denoland/deno/issues/6722#issuecomment-658771957

**To Reproduce**
Rerun benchmarks by returning date and connection headers in Deno/Fastro just like it's done in:
* Test benchmarks repo https://github.com/trivikr/node-deno-http-benchmarks/blob/43e181039a7f7dbc7ef960fc826dbdf33ef2e55f/deno_http.ts#L13-L14
* Deno benchmarks repo https://github.com/denoland/deno/blob/master/std/http/http_bench.ts

**Expected behavior**
Deno/fastro will serve around 25-40% less req/sec when compared to that of Node.js/Fastify

**Comment by ynwd** [comment]
```
const body = new TextEncoder().encode("Hello World");
```
This line make Deno http server serves around 25-40% less req/sec than that of Node.js

**Comment by trivikr** [comment]
> ```
> const body = new TextEncoder().encode("Hello World");
> ```
> 
> 
> This line make Deno http server serves around 25-40% less req/sec than that of Node.js

This line is from code which Deno uses to benchmark itself
https://github.com/denoland/deno/blob/bced52505f32d6cca4f944bb610a8a26767908a8/std/http/http_bench.ts#L9-L17


> Instead of using it, use code samples from the [deno website](https://deno.land/#getting-started)
> 
> ```
> import { serve } from "https://deno.land/std@0.61.0/http/server.ts";
> const s = serve({ port: 8000 });
> console.log("http://localhost:8000/");
> for await (const req of s) {
>   req.respond({ body: "Hello World\n" });
> }
> ```

Fastro should use benchmarking code used by Deno, and not from the code examples.
 
For whoever reading this, it's visible from responses on #6 and #8 that fastro maintainers are not interested in sharing the real benchmarks and want to just boast about fake benchmarks. It won't help in the long run, and gives a bad name for Deno community.

Good news is that there are some serious players among Deno web frameworks (like drash) who take the responsibility https://github.com/drashland/deno-drash/issues/322

**Comment by ynwd** [comment]
@trivikr this benchmark is only to compare the speed of displaying 'hello-world'.

btw, I already update and move the benchmark to https://github.com/fastrodev/fastrodev.github.io/blob/master/benchmarks/deno_http.ts

the speed becomes a little slower.
