### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by newtack** [fastrodev/fastro#9]
I want to have the ability to do fast structured logging. In Node I used roarr for this. I would like to accomplish the same (fast structured logging) in fastro/deno.

I see that there is a logging option, but it is not used yet (e.g. in requestHandler msg variable is populated but does not seem to be actually used). 

Can you clarify the logging story a bit better and ideally align it with roarr's approach?

**Comment by ynwd** [comment]
Oh, sorry. I forgot to include it. Very simple logger will be activated in the next version.

**Comment by ynwd** [comment]
v0.14.0
